spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: verystrongpassword
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

jwt:
  accessExpiration: 3600000
  refreshExpiration: 86400000
  jwtSecret: secretKey